AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: photo album web application

Resources:
  photoalbumui:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "photoalbumui"

  assignment2b2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "assignment2b2" 

  index-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: 
      Description: index photos and update in elastic search
      MemorySize: 
      Timeout: 
      Role: ''
      Environment:
        Variables:
          REGION: us-east-1

  search-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search_photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: 
      Description: Search photos in Elastic Search
      MemorySize: 
      Timeout: 
      Role: ''
      Events:
        ImageBot:
          Type: Api
          Properties:
            Path: 
            Method: 
      Environment:
        Variables:
          REGION: us-east-1
